[versions]
korio = "4.0.10"

[libraries]
korio = { module = "com.soywiz.korlibs.korio:korio", version.ref = "korio" }
korio-jvm = { module = "com.soywiz.korlibs.korio:korio-jvm", version.ref = "korio" }
korio-android = { module = "com.soywiz.korlibs.korio:korio-android", version.ref = "korio" }
korio-js = { module = "com.soywiz.korlibs.korio:korio-js", version.ref = "korio" }
